In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
slice1=arr[2:6]
print(slice1)
slice2=arr[::2]
print(slice2)

[3 4 5 6]
[1 3 5 7 9]


In [2]:
revarr=arr[::-1]
print(revarr)

[9 8 7 6 5 4 3 2 1]


In [3]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarray=arr[0:2,1:3]
print(subarray)

[[2 3]
 [5 6]]


In [5]:
arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[4])
print(arr[-1])
print(arr[1:4])
print(arr[arr>25])
print(arr[1:3])

10
50
50
[20 30 40]
[30 40 50]
[20 30]


In [6]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0,0])
print(arr[1,2])

1
6


In [8]:
# horizontal join
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.hstack((arr1,arr2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [9]:
# vertical join
result1=np.vstack((arr1,arr2))
print(result1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [10]:
# depth join
result2=np.dstack((arr1,arr2))
print(result2)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [16]:
# numpy.array split()
arr=np.array([1,2,3,4,5,6])
result=np.split(arr,3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [21]:
#numpy.array split()
arr1=np.array([1,2,3,4,5,6])
result1=np.array.split(arr,3)
print(result1)

AttributeError: 'builtin_function_or_method' object has no attribute 'split'